### ISSUE TITLE
Retroachievements support

### ISSUE THREAD

**Issue by salvadorc17** [Aftnet/LibretroRT#105]
You will add this feature to the app? the vanilla libretro does support it.

**Comment by AnthroHeader** [comment]
Somehow I don’t think RetriX will be approved for Xbox Live...

Seriously though, not really a priority right now. Cheat support will come before it.

**Comment by LexHDev** [comment]
RetroAchievements has nothing to do with Xbox Live. 
https://docs.retroachievements.org/RALibretro/

Basically RetroAchievements allows for games that are being emulated to have and be able to reward achievements to players on the retroachievements website http://retroachievements.org/

Could this be reconsidered and possibly reopened, a huge reason why I use retroarch over other emulators is the fact it's cross-platform.

**Comment by AnthroHeader** [comment]
Look, achievements are pointlesss to begin with, and doubly so when they are not even part of the original designer’s intent but rather something bolted on many years after the fact.

I see no value in spending development effort and adding a permission for internet access to RetriX to support this.

If you really want this feature though, I’ll give you an option: pay for my dev time at market rate (2-5k USD as a very crude estimate) and I will implement.
