### ISSUE TITLE
IGS PGM (Final Burn Alpha): Bios pgm.zip needs to be set up

### ISSUE THREAD

**Issue by Querpmuerp** [Aftnet/LibretroRT#107]
Hello!
It seems the IGS PGM arcade system needs a bios (pgm.zip), just like the Neo Geo.
At the moment there is no way to set up the bios for this system inside Retrix,
so all you get is a black screen when trying to launch a game (like Knights of Valour, PhotoY2K etc.).
I tried different romsets including fba 2.97.42, which is the version Retrix uses.
Please add this feature, it's a great system and it's already supported by Final Burn Alpha quite good!

**Comment by Querpmuerp** [comment]
I found a solution!
You have to extract the files from pgm.zip and add them directly in the .zip-file of the game. This way I could PhotoY2K to run. I will try it with Demon Front and Knights of Valour later :)

**Comment by Querpmuerp** [comment]
It would be great to set up a bios for PGM just like it is the case for Neo Geo.
But since there's a workaround i will close this issue.

**Comment by AnthroHeader** [comment]
I agree with you: I’ll start looking into this. Right now I can’t find much info about the system on the FBA website though.
