### ISSUE TITLE
Retrix freezing randomly when pausing (with video)

### ISSUE THREAD

**Issue by Querpmuerp** [Aftnet/LibretroRT#108]
v2.1.0.0 on Xbox One S (I noticed it before in older versions too).
When trying to open the pause/save/exit menu (buttons left and right to the xbox-button)
in maybe 1 of 5 times Retrix freezes. The only thing I can do is force quitting and restarting.
This happens in different cores.

In this video I open games on different cores and pause the game: https://youtu.be/bZkxE4zxeqI
Timestamps of the crashes/freezes:
0:19 
1:37
4:03
4:55
6:15
On 6:15 a strange thing happened i never had before. The pause menu is displayed strangely, then the pause bar vanishes and the game just freezes.
If you need any more information, videos or if I should try something special, please let me know.
I really wanna help as far as I can. Btw. the video is not listed, but you should be able to watch it.

**Comment by AnthroHeader** [comment]
This happens when you press select+start on the pad (to bring up the RetriX in-game UI) right?
The glitch at 6:15 is UI artifacts due to RetriX crashing, I've seen it on PC before too.

Edit: yes, it does, I saw it too.

Does this affect the PC too?

**Comment by Querpmuerp** [comment]
Yeah, happens sometimes when pressing select + start (on Xbox One S, wireless gamepad, 1 player signed in). I don't use Retrix on PC cause I got a slow old notebook, maybe someone else can give it a try.

**Comment by Querpmuerp** [comment]
So i tried it on my PC at work. I have no way to connect my Xbox One-controller to my PC, so I paused by moving the mouse on the Retrix game window. I tried different games and paused again and again, but the error did not occour that way.
So maybe it only happens with the Xbox One-Controller or it only happens with Retrix on Xbox One.

**Comment by Querpmuerp** [comment]
I installed two older versions and tried to create the same error when pausing.
Pausing a game works without a problem in 1.8.14.0 and 1.9.4.0!
I noticed pausing in these versions works a bit different. You can first press "select" on the Xbox One pad and then press "start" right after (while still pressing select) to pause. Pressing start first and then select doesn't work, but it works this way in version 2.1.0.0 (but it does not effect on freezing or not in 2.1.0.0.).

So I believe the way pausing was done in these older versions may be the solution. I hope it brings some light into the darkness :)

**Comment by AnthroHeader** [comment]
This is significant: I did change the menu toggling logic for 2.x to make it independent of the button order. I’ll have a look at that section of the code.

Thank you for your help :)

**Comment by Querpmuerp** [comment]
Wow, that sounds promising :)

I thing that I noticed while testing the older versions:
In both 1.8.14.0 and 1.9.4.0 when exiting a game (stop symbol in the pause menu) in maybe 1 of 5 times the game quits and I get back to the Retrix-start page but nothing is highlighted with a white border and I can't select anything at all (no button works). I then have to force quit and restart Retrix. I can't recreate this problem on my PC, only on my Xbox One. Also I never noticed this problem in the current 2.1.0.0 (either on Xbox One or PC, instead the freezes while pausing on Xbox One).

I really appreciate your work! If there's anything I can do, let me know.

**Comment by Querpmuerp** [comment]
One addition that may be helpful for you:
I installed version 2.0.3.0 just for interest (this version had an input error with SNES games,
so pressing start does nothing while playing SNES games).
In this version I can pause with select and start again and again  without freezing, at least in SNES core.

**Comment by Querpmuerp** [comment]
Good news everyone!
I tried the latest version 2.1.1.0 and this issue doesn't seem occur anymore.
Did you change anything regarding this?

**Comment by AnthroHeader** [comment]
Uhm, no. 2.1.1.0 only added support for PolyGame Master and the toggle to force show the touch UI.
To be honest, I never managed to reproduce your issue, but I only have a PC to work with - didn't really know what to do for the Xbox.

I'm happy the issue seems to have gone (maybe Microsoft was at fault and fixed as part of an update?), a bit worried I couldn't figure it out.
