### ISSUE TITLE
I am unable to compile the new source code

### ISSUE THREAD

**Issue by MysteriousHercules** [Aftnet/LibretroRT#13]
I set compile to 64 and test. and it says the following:
1. unsafe code can only be compiled with unsafe.
2. win2d.winmd can not be found

Am I supposed to use retrixshared or retrixuwp?

**Comment by wiired24** [comment]
@MysteriousHercules  The code is still actively being worked on and is far from finished. Probably would be a best idea to wait until the project gets a bit further down the line before compiling it.

**Comment by MysteriousHercules** [comment]
ok. I am new to using GitHub. I thought that making a commit means it is done.

**Comment by wiired24** [comment]
No, A commit just means making some changes to the source tree
