### ISSUE TITLE
Playstation One Core?

### ISSUE THREAD

**Issue by wiired24** [Aftnet/LibretroRT#16]
Hey Alberto,

You've done great work on this project thus far. I was just wanting to see if you had the libretro PS1 core in mind? It's an emulator that alot of people really want. I'd be super excited to see it on Retrix. 

These are just a couple PS1 Libretro cores that I found 
https://github.com/libretro/beetle-psx-libretro
https://github.com/simias/rustation-libretro

Thanks, all the best

**Comment by albertofustinoni** [comment]
Hello

I do have PS1 core in mind too, however there are a few more technical hurdles to overcome to get them to work in UWP.

Also, at this point I am focusing on the UI: I want to have something I am satisfied with before I push forward with adding further cores.

**Comment by wiired24** [comment]
Hey Alberto,

That's good to hear, I totally understand where you are coming from with wanting to get the U.I. done right first before moving forward with more cores. Keep up the good work
