### ISSUE TITLE
Saving and loading?

### ISSUE THREAD

**Issue by wiired24** [Aftnet/LibretroRT#23]
Hey Alberto I noticed on one of your recent commits it showed you were working towards Save/Load states?  I did a git clone of the latest version of LibretroRT (Nice work on the UI btw) and I'm not exactly sure how to save or load the game. Is there a button that's mapped to saving and loading or does it just work in game?

Thanks,

**Comment by MysteriousHercules** [comment]
did you get the latest build of libretro to compile?

**Comment by wiired24** [comment]
Re-read my comment I just said I did.

**Comment by wiired24** [comment]
It's not difficult to compile at all.

**Comment by MysteriousHercules** [comment]
thank god, I will test it. I will look in the code as well. if I find out something about save/load state. I will let you know.

**Comment by albertofustinoni** [comment]
There are two ways of saving loading: via the overlay when playing games (press save button on bottom left, select slot and to save/load) or via keyboard shortcuts (Alt+F1..F6 to save or just F1...F6 to load)

There are also shortcuts to enter exit full screen (Shift+Enter to toggle, escape to exit), or just double click/tap on the game image itself. The idea is to make RetriX work like a video player.

**Comment by wiired24** [comment]
But how would you save on the Xbox? That's what I'm testing it on

**Comment by wiired24** [comment]
Nevermind I fixed it by just commenting out the line of code that disables the mouse cursour in the App.xaml.cs file.  it's needed to bring up the overlay for the Xbox One

**Comment by albertofustinoni** [comment]
I have an idea for how to implement in game UI when only a gamepad is available (Xbox) and plan on doing it in the future.

Right now though my main issue is that I don't have an Xbox to test RetriX on...

**Comment by wiired24** [comment]
I'm your guy then. I do have an Xbox One and I can test it and have been haha
