### ISSUE TITLE
OpenGL ES in C# to UWP

### ISSUE THREAD

**Issue by WodsonKun** [Aftnet/LibretroRT#3]
Why don't add a DX11 backend, instead of using ANGLE? @hrydgard did this with the UWP port of PPSSPP...

**Comment by albertofustinoni** [comment]
Because that would mean rewriting a good chunk of whatever cores I'd be using.

Libretro core authors do not usually target DirectX because it's Windows only.

I'm trying to get as many cores working on UWP as possible and write a front end, not developing the cores themselves.

**Comment by DarkLegend481** [comment]
This port will come to ARM too?

**Comment by albertofustinoni** [comment]
If I can get it to work, sure.

Some of these cores go pretty low level with their optimizations, which means changes in instruction set/endianness may break them.

**Comment by DarkLegend481** [comment]
If you compile it for me (I do not have a PC to compile ☹), I can test ARM on a real device (I have a Lumia 635) and report to you the performance of the emulator, how many FPS each core runs, etc...

Unless you have a Windows 10 Mobile device...

**Comment by albertofustinoni** [comment]
Thank you for the offer; I have a Lumia 950 and a 640 myself so I should be able to test.

Right now I can't seem to get the project to build in release mode and am trying to figure out what's wrong

Keep also in mind the app has zero support for touch screen, so you would have no way of actually playing games on it

**Comment by MysteriousHercules** [comment]
I have a question, I am not able to build the code because it keeps saying "libretroRT.winmd". What should I do? Also, do I choose libretroRt.test, or just test for compiling.

**Comment by DarkLegend481** [comment]
@MysteriousHercules Send a screenshot with the problem or a log file...

Maybe with that, @albertofustinoni can help you 😁

**Comment by MysteriousHercules** [comment]
![libretro compile](https://cloud.githubusercontent.com/assets/28547332/26658016/5139e328-461c-11e7-898b-a215403091fa.png)

Here is what I have, let me know if there is something else I need to know to compile the code and test it.

**Comment by WodsonKun** [comment]
@albertofustinoni

Do you speak Portuguese? / Você fala Português?

When the touch screen controls come?

**Comment by albertofustinoni** [comment]
No I am Italian, the most I manage is some Spanish or Japanese apart from English.

I am wondering whether to add touch controls or require a keyboard/gamepad: these are not mobile games and playing them on with touch screen controls is a miserable experience.

**Comment by WodsonKun** [comment]
But, some Lumia like my 635 doesn't have USB OTG support, making RetriX inutile on it... (Sorry about my English 😅)

**Comment by WodsonKun** [comment]
Hey, you will try launch it on Windows Store? I heard that Microsoft removes the emulators after they are in the store...

Hey... Will you use GLupeN64 or Mupen64 core to Nintendo 64?

**Comment by WodsonKun** [comment]
Wait... I will make a new issue only for Core requests and Core issues

**Comment by JimSEOW** [comment]
@albertofustinoni  I started [OpenGLES UWP XAML c#.](https://github.com/Microsoft/angle/issues/125) Would be great if you could comment. I understand that your UWP OpenGLES UserControl are in C++ instead of C#. I guess I probably has to do that as C# OpenGLES XAML suck

**Comment by WodsonKun** [comment]
Re-opening...

**Comment by WodsonKun** [comment]
Opening a new issue...
