### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by mrsilver76** [Aftnet/LibretroRT#32]
Looks lovely from the video. I like the way you're trying to do for retro-gaming what VLC did for video playback. As in, simple, easy and just works.

Having said that, is there any chance you could provide binaries? I tried to compile it in Visual Studio 2017 and it failed to compile with a whole tonne of errors.

I also had to download about 2GB of additional files - so I suspect this will put off a lot of other people (which is a shame, because it looks great).

**Comment by albertofustinoni** [comment]
Did you do a recursive clone? The code for Libretro cores is included as submodules, and hit by default does not initialize those. Cloning from Visual Studio's team explorer also does the trick.

I really want to do binary releases for people to side load easily, but to do without forcing people to trust a random self signed certificate I need to get myself an Authenticode certificate, and they are not cheap. I have opened a [gofundme](https://www.gofundme.com/retrix) to help fund development

**Comment by MysteriousHercules** [comment]
Also did you make sure to compile only the 64 bit version as well as retrix uwp as your start project. one thing that helped me compile the code was highlighting retrix uwp on the right, clicking on project tab at the top, then clicking on store, then clicking on creating app package, then making sure it always loads x64 bit only

**Comment by mrsilver76** [comment]
Sounds like I've done it wrongly. Will have another go when I get a chance. Thank you both.

If the build steps were documented in the readme.md then that would be really good.

**Comment by albertofustinoni** [comment]
Good point, added some build instructions in the readme

**Comment by albertofustinoni** [comment]
I have started providing binaries for RetriX: linksin the front page. Closing this issue.
