### ISSUE TITLE
Certificate local installation manual

### ISSUE THREAD

**Issue by areyouokani** [Aftnet/LibretroRT#34]
Link this one to your readme, it's infinitely more coherent and easy to use.

http://www.thewindowsclub.com/manage-trusted-root-certificates-windows

**Comment by albertofustinoni** [comment]
Updated link to [this one](http://www.sqlservermart.com/HowTo/Windows_Import_Certificate.aspx). Same instructions but bigger pictures so hopefully easier to follow
