### ISSUE TITLE
A certificate with thumbprint that is specified by project is not found in store?

### ISSUE THREAD

**Issue by MysteriousHercules** [Aftnet/LibretroRT#39]
I got an error when I tried to compile the source code that says the following :" A certificate with thumbprint that is specified by project is not found in store"

I get this error only when creating the app package.

**Comment by albertofustinoni** [comment]
That is normal: as I am signing packages the project is configured to look for my private key (the one matching the public key in the certificate in the Github releases section) when creating app packages.

To make your own app packages go to the manifest editor and generate a new signing certificate in the packaging section.

**Comment by MysteriousHercules** [comment]
thank you

**Comment by albertofustinoni** [comment]
You are welcome
