### ISSUE TITLE
Key mapping

### ISSUE THREAD

**Issue by wileymarques** [Aftnet/LibretroRT#41]
I'm unable to make a gamepad or keyboard work on mobile.
Is there a way to configure key mapping?

**Comment by albertofustinoni** [comment]
No, there is no key mapping right now.

What game pad are you trying to use? An Xbox One pad?

**Comment by wileymarques** [comment]
I tried an Ípega that can emulate a keyboard, but needs a key configuration, of course.

And a Xbox 360 game pad, through USB.

What are the keys currently working?

**Comment by albertofustinoni** [comment]
current key bindings are: arrow keys for directions, O for select P for start, A-S-D-Z-X-C for face buttons.

Weird that the Xbox pad isn't working: RetriX should be compatible with any Xinput compatible gamepad.

**Comment by wileymarques** [comment]
I'll see if I can make some config page for this!
