### ISSUE TITLE
OpenGL ES in C# to UWP

### ISSUE THREAD

**Issue by WodsonKun** [Aftnet/LibretroRT#45]
@JimSEOW started working on a OpenGL ES port in C# for UWP based in a C++ template of OpenGL ES.

I opened this issue to discuss about it...

**Comment by JimSEOW** [comment]
@WodsonKun  if people are interested , [here is the link to the discussion](https://github.com/Microsoft/angle/issues/125)

**Comment by albertofustinoni** [comment]
While it is an interesting project, I cannot use a C# binding of Angle in RetriX for two reasons:

- LibretroGL makes heavy use of function pointers, C# does its best do hide pointers of any kind from the programmer. If it is even possible, it would be a lot more complex than just using C++.
- To work around the breaking issues with window resizing in Angle, I am using Angle's OpenGL contex to render to a texture, which I import in the Direct3D context used by Win2D. This requires some COM trickery which is impossible to do in C#.

**Comment by JimSEOW** [comment]
@albertofustinoni 
I think OpenGLES for C# is much more promising through the [Angle Implementation in SkiaSharp.View](https://github.com/Microsoft/angle/issues/125#issuecomment-314914592)
