### ISSUE TITLE
Scanline support on XBox One?

### ISSUE THREAD

**Issue by fionncroke** [Aftnet/LibretroRT#75]
Just wondering if this is a high priority feature. Not a big fan of the blurry bi-linear overlays

**Comment by albertofustinoni** [comment]
It's not.

Tbh i don't get the fascination with scanlines to begin with; it will come if/when I get shader support working for stuff like HQXn

**Comment by fionncroke** [comment]
Ok no problem. Thanks for the quick reply! Incredible work on the project, much support. :)
