### ISSUE TITLE
IMemoryBufferByteAccess is preventing me from creating app package

### ISSUE THREAD

**Issue by MysteriousHercules** [Aftnet/LibretroRT#8]
I have successfully managed to successfully build and run the retrix app. The problem is I am not able to create app package. Everytime I do, I get:
"
Severity	Code	Description	Project	File	Line	Suppression State
Error		ILT0021: Could not resolve method 'System.Void LibretroRT.AudioGraphPlayer.AudioPlayer.IMemoryBufferByteAccess__LibretroRT_AudioGraphPlayer__Impl.Stubs.GetBuffer(System.__ComObject, ref System.Byte*, ref System.UInt32)'	Test			
"

I went to that line, and I noticed it said unsafe. I am not sure if that has something to do with it. But I felt I needed to point that out.

**Comment by albertofustinoni** [comment]
That is the issue I referred to whe I said I was looking into what was preventing me from building in release.

I believe it to be a compiler issue and have reported it to Microsoft. Will see what they say about it.

**Comment by MysteriousHercules** [comment]
ok, thank you so much

**Comment by MysteriousHercules** [comment]
Any update on the issue, did Microsoft say anything back?

**Comment by albertofustinoni** [comment]
[They did](https://github.com/dotnet/roslyn/issues/19942#issuecomment-306861036)

They gave me some possible workarounds, which I'll have to try out, but the issue itself will take some time to fix.

**Comment by albertofustinoni** [comment]
Fixed this.
