### ISSUE TITLE
Unable to pull full source

### ISSUE THREAD

**Issue by billsargent** [Aftnet/LibretroRT#82]
I'm getting the following error when trying to reursively clone the source.

Unable to checkout '659442f88c9eb49a8033f5841bedbf953698a96c' in submodule path 'MelonDS/src'

**Comment by WodsonKun** [comment]
MelonDS...
Always giving trouble kkkkkkkkk

**Comment by cedricstanus** [comment]
Me too, impossible to get the entire project, i've the same error.
So impossible to build

**Comment by albertofustinoni** [comment]
Ok, this is kinda weird.

Since it's a submodule, the issue should be with MelonDS's repo I think.

**Comment by JimmyRespawn** [comment]
Try to compile it via direct download the zip. No go either. Anyway to share the clean project?(without bins and obj folders)

**Comment by albertofustinoni** [comment]
Should be fixed now.
