### ISSUE TITLE
trying to compile cores and add them in retrix

### ISSUE THREAD

**Issue by MysteriousHercules** [Aftnet/LibretroRT#9]
I managed to understand a big part of the coding process. and I am going to try and add some cores to help you.

The only question I have is where do you get the source code for the emulator cores you use. Do you take them from retroarch and then convert them to retrix. or do you get the source code from somewhere else?

I apologize if this is the wrong place to ask this question. If it is, I will delete this issue.

**Comment by WodsonKun** [comment]
FCEUMM = https://github.com/libretro/libretro-fceumm/tree/master

I got it on files...
