### ISSUE TITLE
Xbox Wireless Controller Not Working

### ISSUE THREAD

**Issue by zsKengren** [Aftnet/LibretroRT#92]
Hello,

I am having an issue where the wireless controller is not working when loading any of the cores. I have tried to load nes, snes, mega drive, and playstation. Once I load retrix, I am able to navigate around and select the core and game but once the game loads, I am not able to do anything in the game. I am able to exit the game so the xbox is receiving commands from the controller but I am not able to play the actual game. 

It does work however when I plug in with a USB cable.

Is any one else having this issue?

Thanks,
zs
  

I just saw that you released a new version today. I will give that a try tonight.

**Comment by zsKengren** [comment]
I tried to apply the update and test again. This time the wired controllers didn't work either.

**Comment by albertofustinoni** [comment]
I think you may have an issue with your system. Controllers work as they should for me.
