### ISSUE TITLE
Can't install the app in mobile

### ISSUE THREAD

**Issue by danton03** [Aftnet/LibretroRT#98]
I tried installing RetriX on my lumia with windows 10 mobile but I could not, the app does not appear even after installing the dependencies. Ps .: I followed the instructions on the wiki and tried it in other ways as well. The code error is 0x80073cdf (A Prerequisite for an install could not be satisfated).

**Comment by beavermml** [comment]
Have you enable the developer kode?

**Comment by danton03** [comment]
Yes, I'm using development mode. I've almost tried to install this app in all ways: Following Wiki instructions, using programs to deploy, using the Microsoft device center, installing with dependencies, without dependencies, using Interop Tools .... I've tried with ALL versions available here and the reported error is always the same. But the error displayed varies a bit according to the mode of installation that I try. Until Hard Reset on the smartphone I made to try to install. I will leave below the screenshots I took while trying to install the app.
![centro de dispositivos](https://user-images.githubusercontent.com/37675973/38468313-4bdcadd6-3b1a-11e8-9e4f-39e7d669ac31.PNG)
![windows phone application deployment 8 1](https://user-images.githubusercontent.com/37675973/38468339-a5752148-3b1a-11e8-9960-0482144489f1.PNG)
![interop tools-deployment mode](https://user-images.githubusercontent.com/37675973/38468384-4cf30642-3b1b-11e8-9264-94223f256480.png)
![interop tools-force application shutdown](https://user-images.githubusercontent.com/37675973/38468385-53dd43dc-3b1b-11e8-9d55-821c7247187b.png)

**Comment by Petrillion** [comment]
Hey. I have the same problem using a Lumia 830 with Windows Version 10.0.14393.2248 and i simply can't install this app...
Did you find any solution?

**Comment by danton03** [comment]
No, I simply tried in every way I could think of with all the releases available here. I think somehow the app is no longer supported in the latest versions of Windows 10 Mobile or Appx needs to be recompiled. I will test the latter next week when I have access to a PC with Visual Studio.

**Comment by AnthroHeader** [comment]
Just got the notification about the thread. Two things to notice:

1. The latest Windows Mobile is 15063
2. RetriX targets that version (Creators Update)

**Comment by danton03** [comment]
In other words, it no longer works on legacy Lumias. It is? :/

**Comment by AnthroHeader** [comment]
No, RetriX never worked on versions prior to 15063 to begin with. Sorry to have to bring bad news.

**Comment by Petrillion** [comment]
Hey, finally found a solution to update from 14393 to 15063.
Here's a link. It worked for me (Lumia 830) and Retrix runs flawlessly.

http://allaboutwindowsphone.com/features/item/22816_How_to_2018_edition_Take_the_L.php

**Comment by mediaexplorer74** [comment]
> No, RetriX never worked on versions prior to 15063 to begin with. Sorry to have to bring bad news.

You're wrong. RetriX works on W10M build 14939 normally. It was only your "pleasure" to set min. win. OS build = 15063. ;)
